### PR TITLE
Pilot3 Website - Latest News Update - RCWG Meeting Minutes April 2024…

### PR DESCRIPTION
**Pull request by robertdevine**
… and May 2024 Editions. **Did not make any changes to the Pilot3 lock file.**

### CODE REVIEW

**Comment by robertdevine** [comment]
Interesting, the PharmaSUG 2024 URL is failing in the check. Let me take a look. Passed in the March 2024 website build. Thx.

image

**Comment by bms63** [comment]
I think we modified the lock file since the last time we published - unclear if this will work.  might need to go back and get feb and march's version of the lock file

**Comment by robertdevine** [comment]
Yes, the lock file for both February 2024 and March 2024 Pilot3 website updates with the RCWG links have the pilot1wrappers references. Also, I the link RCWG to the April 2024 website update is different than all previous monthly updates and the May 2024 update. Best to have consistency. Thx.

**Comment by bms63** [comment]
I'm more concern that the pgkdown and other website building packages were removed.  The CI action pulls that in from the lock file to build the site

**Pull request merged**
