### PR TITLE
Pilot3 Submission Team Check In - Meeting Minutes update for February…

### PR DESCRIPTION
**Pull request by robertdevine**
@bms63 or @laxamanaj please review the meeting minutes from today's Check In. Thank you.

### CODE REVIEW

**Comment by bms63** [comment]
These look great!  How are you making them?

**Review by laxamanaj — COMMENTED** [review]
Just reviewed and these look great, @robertdevine .  Though I saw the .RMD wasn't updated, can I ask how you updated the .pdf?

**Comment by laxamanaj** [comment]
Thanks again, Robert. Now in main.

**Comment by robertdevine** [comment]
Thanks @laxamanaj. Requested review on the verbiage (10Feb2023) before final merge to main including the minutes from previous 2023 Check Ins. Should be all set to proceed with .RMD (i.e. pdf_document output) moving forwards. Thanks again.

**Comment by bms63** [comment]
Should we update the `Rmd` file so the next person can have the updated minutes??

**Comment by robertdevine** [comment]
@bms63 the Rmd should already be sync'd including yesterday's (10Feb2023) Check In minutes and all previous 2023 Pilot 3 Team Submission Check In minutes.  Thank you.

**Comment by laxamanaj** [comment]
I updated the minutes from the past meetings and added @robertdevine ‘s , from yesterday, to the .Rmd, now in main. We should be up to date now.

**Pull request closed without merging**
