### PR TITLE
Add Pilot3 Website Home Page Latest News Section

### PR DESCRIPTION
**Pull request by robertdevine**
Added a Latest News section to the Pilot 3 website home page and two bullets: [i]the R Consortium Blog Announcement page, and [ii]a blurb with YouTube link about the Novo Nordisk submission journey.

### CODE REVIEW

**Comment by robertdevine** [comment]
Thanks @bms63.

**Review by laxamanaj — APPROVED** [review]
I like these udpates.  Thanks @robertdevine for updating. I approve.

**Comment by robertdevine** [comment]
Thanks @laxamanaj. Yes, a 'Latest News' section provides a way for the Pilot3 home page to link/connect community news. Pretty cool. Thanks again.

**Comment by laxamanaj** [comment]
Looks like the pkgdown check didn't pass, but I did see that the deploy passed the checks.  Website still now showing latest news.

**Comment by robertdevine** [comment]
The merged PR looks fine in GH but the CDN has not updated the Pilot3 home page (yet). [Does seem a bit slow.] Thanks.

image

**Pull request merged**
