### PR TITLE
Closes #77 update renv.lock

### LINKED ISSUE #77: update renv.lock to use admiral v0.10.0
Hi, @DeclanHodges .  If you have bandwidth, I hope you can help with this.  
cc : @bms63

### PR DESCRIPTION
**Pull request by DeclanHodges**
renv.lock is now using package versions from 2023-03-14 snapshot via Posit Package Manager.

### CODE REVIEW

**Comment by DeclanHodges** [comment]
I've updated to use the snapshot from 15th March rather than 14th, as rlang <= v1.1.0 is required to load haven, which only seems to be available from 15th onwards.

**Comment by DeclanHodges** [comment]
After test runs of the datasets/displays following the renv.lock update, we have some points which need addressing:
- ADADAS: erroring from call to `pilot3::derive_locf_records_()`, due to switch to using `exprs()` in `admiral`. Should be addressed once using `admiral::derive_locf_records()` (#78).
- ADTTE: erroring from call to `xport_write()` (we have now up-versioned to `xport` v0.2.0 which I assume is causing this).
- ADSL: receiving lifecycle warnings due to `derive_vars_disposition_reason()` and `derive_var_disposition_status()` entering the deprecation cycle in `admiral`, however the functions remain available in 0.10.1. Since we plan on keeping the `admiral` version static, do we want to keep them in the code or replace with the superseding functions for the sake of removing the warnings?
image


ADLBC, ADAE and all the displays look to be running okay with the new package versions.

**Review by bms63 — APPROVED** [review]
Looks good to me!

**Comment by bms63** [comment]
> After test runs of the datasets/displays following the renv.lock update, we have some points which need addressing:
> 
> * ADADAS: erroring from call to `pilot3::derive_locf_records_()`, due to switch to using `exprs()` in `admiral`. Should be addressed once using `admiral::derive_locf_records()` ([locf derivation in admiral v0.10.0 - check that datasets that use this derivation that all is working ok now. #78](https://github.com/RConsortium/submissions-pilot3-adam/issues/78)).
> * ADTTE: erroring from call to `xport_write()` (we have now up-versioned to `xport` v0.2.0 which I assume is causing this).

Why is this the only one that is failing?

> * ADSL: receiving lifecycle warnings due to `derive_vars_disposition_reason()` and `derive_var_disposition_status()` entering the deprecation cycle in `admiral`, however the functions remain available in 0.10.1. Since we plan on keeping the `admiral` version static, do we want to keep them in the code or replace with the superseding functions for the sake of removing the warnings?

I think we should upgrade to the new process - folks will be looking at this code down the road and be nice to try ann get things up to date.  Hopefully, admiral will not change too much!!

>   image
> 
> ADLBC, ADAE and all the displays look to be running okay with the new package versions.

**Review by laxamanaj — APPROVED** [review]
Thanks, @DeclanHodges for updating the renv.lock file and CRAN snapshot.  I do also see the updates to vars() to exprs() with the new admiral call. Will merge these updates to main now.

**Pull request merged**
