### PR TITLE
Tidying tlf-demographic.Rmd removing {pilot1wrappers} package dependency.

### PR DESCRIPTION
**Pull request by robertdevine**
This change does not affect the lock file. Re-testing output before pushing report-tlf.pdf with refreshed timestamps. thx.

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Does it need pilot3utils to run?

**Comment by robertdevine** [comment]
No, this is backlog related historically in Pilot3 to [Agency Comment 3](https://github.com/RConsortium/submissions-pilot3-adam/files/14915906/Pilot3_response_to_fda.pdf). The {pilot1wrappers} reference dependency remained from when the {pilot3} name was used prior to the Pilot3 Team addressing the agency comments. Checking the other vignettes (and non-submission articles for any other strays). Thx.

Checking the programs and outputs with the Pilot 3 Team responses and if all goes well will refresh tlf-report and clean up the (non-submission) vignettes as well of the {pilot1wrappers} reference. 

image

**Review by laxamanaj — COMMENTED** [review]
Many thanks for this @robertdevine .  Looks good to me.  Did the other output programs need the call to pilot3utils as well?

**Review by laxamanaj — APPROVED** [review]
Approve otherwsie, if these were the only 2 programs that needed to be updated.  Thanks for this.

**Comment by robertdevine** [comment]
Yes, @laxamanaj , the Pilot3 assembly is now free of the {pilot1wrappers} dependencies and namespace overlaps with the former {pilot3} naming. Per the Agency feedback, the proprietary package is named {pilot3utils}. The vignettes have been updated removing the library references to {pilot1wrappers} and the namespaces for the function calls has been changed from {pilot1wrappers} namespace to {pilot3utils} namespace. So, in summary, if the .zip archive installation instructions are used the programs and outputs run correctly and the tlf-report.pdf with refreshed timestamps is generated. Should be all set. Thanks.

image

**Comment by bms63** [comment]
Hi all,

Still a little confused on this.  We need to re-create the report of the outputs?  Does this .rmd and pdf need to get updated as well? 
image

**Comment by robertdevine** [comment]
A bit of history may help explain, @bms63 

Pilot1 (OS: ubuntu v20.04) used _libreoffice_ to generate the primary endpoint analysis
outputs rtf-to-pdf conversions to create the Pilot1 tlf-report.pdf [here](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf).

For purposes of consistency, [Pilot3](https://github.com/RConsortium/submissions-pilot3-adam/blob/main/submission/programs/report-tlf-pilot3.pdf) did the same back in August. The cloud service provider 
declined to install libreoffice (Ubuntu) citing a security concern. To address that constraint, 
the primary output rtf-to-pdf conversions used to generate the Pilot3 tlf-report.pdf  
were generated locally by @laxamanaj and @robertdevine (then confirmed identical) for 
the August submission. @laxamanaj j pushed the tlf-report.pdf to the Pilot3 FDA repo here. 
For consistency, to refresh the timestamps for the re-submission the same steps apply in 
which case no additional code changes are necessary.

On Friday I did confirm above the process used by Pilot3 to generate the tlf-report.pdf
(with refreshed timestamps) does work. @lj should be all set to re-perform the exact steps 
performed locally for the August 2023 regulatory submission. 

For consistency, the same process to re-fresh timestamps should be followed for the re-submission.
Takes just a few minutes for @laxamanaj to complete the cycle and push here.

The **>soffice --convert-to pdf** [command is used and works with primary and efficacy rtf-to-pdf.]

image

Lastly, Pilot3 also innovated other techniques to perform this conversion including the browser engine - anyone
reading these chains who has time to research the rich history of Pilot3 can explore more about that in the Pilot3 
discussion threads.

Should be all set on this. item. @laxamanaj please let me know if you need me to upload the refreshed report
to the FDA repo [here](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m1/us/report-tlf-pilot3.pdf).

Thanks.

**Comment by bms63** [comment]
Awesome.  So we just need to rerun the code to get the refreshed report. @laxamanaj explained this to me a bit more on Firday.  I was confused and I thought this PR was going to generate it, but now I understand he needs to re-run it.

Do we need to document or put instructions anywhere?  If there isn't any...??

**Comment by robertdevine** [comment]
Up to you @bms63 and @laxamanaj, if so, please create the issue and I'll self-assign to write up a document. Thx.

**Comment by bms63** [comment]
I think we should note the process somewhere?   I'm not sure where - maybe just in the related `.Rmd` file that complies everything?

**Comment by robertdevine** [comment]
@bms63, @laxamanaj - will document in [here](https://github.com/RConsortium/submissions-pilot3-adam/issues/183). thx.

**Comment by laxamanaj** [comment]
> A bit of history may help explain, @bms63
> 
> Pilot1 (OS: ubuntu v20.04) used _libreoffice_ to generate the primary endpoint analysis outputs rtf-to-pdf conversions to create the Pilot1 tlf-report.pdf [here](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf).
> 
> For purposes of consistency, [Pilot3](https://github.com/RConsortium/submissions-pilot3-adam/blob/main/submission/programs/report-tlf-pilot3.pdf) did the same back in August. The cloud service provider declined to install libreoffice (Ubuntu) citing a security concern. To address that constraint, the primary output rtf-to-pdf conversions used to generate the Pilot3 tlf-report.pdf were generated locally by @laxamanaj and @robertdevine (then confirmed identical) for the August submission. @laxamanaj pushed the tlf-report.pdf to the Pilot3 FDA repo [here](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m1/us/report-tlf-pilot3.pdf). For consistency, to refresh the timestamps for the re-submission the same steps apply in which case no additional code changes are necessary.
> 
> On Friday I did confirm above the process used by Pilot3 to generate the tlf-report.pdf (with refreshed timestamps) does work. @laxamanaj should be all set to re-perform the exact steps performed locally for the August 2023 regulatory submission.
> 
> For consistency, the same process to re-fresh timestamps should be followed for the re-submission. Takes just a few minutes for @laxamanaj to complete the cycle and push to the Pilot3 FDA repo.
> 
> The **>soffice --convert-to pdf** [command is used and works with primary and efficacy rtf-to-pdf.]
> 
> image
> 
> Lastly, Pilot3 also innovated other techniques to perform this conversion including the browser engine - anyone reading these chains who has time to research the rich history of Pilot3 can explore more about that in the Pilot3 discussion threads.
> 
> Should be all set on this. item. @laxamanaj please let me know if you need me to upload the refreshed report to the FDA repo [here](https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m1/us/report-tlf-pilot3.pdf).
> 
> Thanks.

Hi, @robertdevine .

Many thanks for generating the report.  I believe at this time, any one of us could regenerate this.  I've already refreshed all of the ADaMs and outputs as of 12Apr2024 (https://github.com/RConsortium/submissions-pilot3-adam/tree/main/submission/output) . Though, I did not convert the .rtf to .pdf to generate the the `report-tlf.pdf`. @robertdevine , if you have already done these steps and the `report-tlf.pdf` is now refreshed with the update time stamps feel free to push the `report-tlf.pdf`, then we can merge this to main, then copy the report to the fda repo.

**Comment by laxamanaj** [comment]
Hi, @bms63 , @kaz462 , @SHAESEN2 , @AlexandraP-21  and @robertdevine .

As my last commit message says, I've rerun the outputs with today's timestamps and did a manual combine of the outputs into pdf as our current issue we have yet to resolve is the automated rtf to pdf conversion.  Though the latter has no impact on the results, just a formatting issue which can be resolved at a later time (i.e. local libreoffice install, then run this function : https://merck.github.io/r2rtf/articles/rtf-convert-format.html ).

To note here, these are the steps I took.

1. I first ran this .rmd : https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/programs/report-tlf-pilot3.Rmd . In this .Rmd you'll notice that only the demog and the kmplot were refreshed and output into pdf using this markdown file. 
2. I then reran https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/programs/tlf-efficacy.r and https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/programs/tlf-primary.r, interactively.  Both of these output these 2 files : https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/output/tlf-efficacy-pilot3.rtf and https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/output/tlf-primary-pilot3.rtf, respectively.
3. I then downloaded the pdf generated in step 1 and the .rtf outputs in step 2.
4. For the tlf-efficacy-pilot3.rtf, I opened using WordPad on my local Windows PC.  I then resaved this file as a .pdf. This is manual conversion number 1.
5. For the tlf-primary-pilot3.rtf, I opened using PDF-Xchange-editor on my local Windows PC.  I then resaved this file as a .pdf. This is manual conversion number 2.
6. Then I brought in all pdfs from steps 1, 4 and 5 and combined them using functionalities in the PDF-XChange-editor to create this : https://github.com/RConsortium/submissions-pilot3-adam/blob/177-refresh-report-tlfpdf/submission/programs/report-tlf-pilot3.pdf 

Please review this new pdf in step 6 and compare against this output in Pilot 1 https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf.  All results should match. 

Upon your review, if these match up, then this branch can now be merged into main to close out.  Then we can just download the final output in step 6 and bring over to the pilot 3 adam to fda repo.

Best,
Joel

**Comment by robertdevine** [comment]
Thanks @laxamanaj - very cool. As noted [here](https://github.com/RConsortium/submissions-pilot3-adam/pull/178#issuecomment-2054234286), **>soffice --convert-to pdf** command (in libreoffice) was
used by @robertdevine during August 2023. It will be interesting to run using the Merck wrapper
 rtf-convert-format. Pretty cool. Thx. again.

**Comment by laxamanaj** [comment]
Thanks @robertdevine .

Hoping to get feedback that the results from the current report-tlf-pilot3.pdf I generated still matches the pilot1 report-tlf.pdf, which I've linked above. I just need a second pair of eyes to confirm in a comment, then I can merge.

Or if the results match to you @bms63 then please merge as soon as you complete review.

Thanks.

**Pull request merged**
