### PR TITLE
Setup CI pipelines

### PR DESCRIPTION
**Pull request by bms63**

### CODE REVIEW

**Comment by bms63** [comment]
Got some things to work through here.

**Comment by bms63** [comment]
@thomas-neitmann  I think most of these are pretty quick fixes.  Are we building a R package or are we just using the infrastructure for documentation and testing?

**Comment by thomas-neitmann** [comment]
Thanks a lot @bms63!

Looks like some easy fixes to get the workflows passing indeed. I'll take a look and push some updates here. We are in fact building an R package that we'll submit to the FDA alongside our scripts.

**Comment by thomas-neitmann** [comment]
@bms63 I fixed almost all issues. The last remaining one is from `R CMD check`:

```
   Undefined global functions or variables:
     %>% 54 81 AVISITN as_tibble case_when ci confint contrast diff_se
     drop1 filter lm ord ord_layer_1 ord_layer_2 ord_layer_index p p.value
     row_label row_label1 row_label2 rowwise tibble value
```

Would you mind fixing this? If not I'll get to it sometime later this week.

**Review by thomas-neitmann — APPROVED** [review]

**Pull request merged**
