### PR TITLE
10 update define

### PR DESCRIPTION
**Pull request by laxamanaj**
updating define after updated from #82 . I reopened #10 just to test out new final define in P21.

Rerunning P21, we are looking good.  Same 2 issues as before. QC findings updated in wiki.

image

### CODE REVIEW

**Comment by kaz462** [comment]
@laxamanaj Thanks for the updates! 
I've rerun all qc programs and checked with [qc findings](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings#adadas), only have one comment - 
`ADAE.ADURU` is "DAYS" in the dataset, but it's "DAY" in the define. 

For ADADAS, I elaborated more about the cause of discrepancies in [qc findings](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings#adadas)

**Comment by laxamanaj** [comment]
Hi, @kaz462 . I checked the specs in this branch that are read from the `adam` folder in this branch, but I do see it's shows 'DAYS'.  Can you let me know which define you are looking at?  Thanks.

**Review by kaz462 — APPROVED** [review]

**Comment by kaz462** [comment]
@laxamanaj sorry I looked the wrong one, LGTM 👍

**Comment by laxamanaj** [comment]
with new define and updated R scripts, I ran pinnacle 21 enterprise v5.2 with consistent issues as before.
image

Similarly, I also ran same package on Pinnacle 21 community version (Pinnacle 21® Community 4.0.1). Showing same issue : 
image

At this time, we can now merge all to main.

**Comment by laxamanaj** [comment]
Re-opening #10  from this PR to include #101 .  Thanks, @kaz462 for noticing.

**Pull request merged**
